In [1]:
import numpy as np

In [2]:
arr = np.arange(0,50,5)
arr

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45])

In [3]:
arr[0]

0

In [4]:
arr[4]

20

In [5]:
arr[-1]

45

In [6]:
arr[0] = 99
arr

array([99,  5, 10, 15, 20, 25, 30, 35, 40, 45])

In [7]:
arr[:]

array([99,  5, 10, 15, 20, 25, 30, 35, 40, 45])

In [8]:
arr[:3]

array([99,  5, 10])

In [9]:
arr[1:-1] = 50
arr

array([99, 50, 50, 50, 50, 50, 50, 50, 50, 45])

In [10]:
arr = np.arange(0,50,5)
arr

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45])

In [11]:
sub_arr = arr[0:4]
sub_arr

array([ 0,  5, 10, 15])

In [12]:
sub_arr[:]=50
sub_arr

array([50, 50, 50, 50])

In [13]:
arr

array([50, 50, 50, 50, 20, 25, 30, 35, 40, 45])

In [14]:
arr = np.arange(0,50,5)
cop_arr = arr.copy()
cop_arr

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45])

In [15]:
cop_arr[:]=50
cop_arr

array([50, 50, 50, 50, 50, 50, 50, 50, 50, 50])

In [16]:
arr

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45])