In [1]:
import numpy as np
arr = np.random.randint(0,4,10)
arr

array([0, 2, 2, 3, 3, 0, 1, 3, 0, 1])

In [2]:
np.unique(arr)

array([0, 1, 2, 3])

In [3]:
np.in1d([-1,3,2],arr)

array([False,  True,  True])

In [4]:
arr_1 = np.random.uniform(-5,5, size=[3,2])
arr_1

array([[-1.86926153,  0.38268722],
       [-3.97913744,  2.40503128],
       [ 3.57102452,  4.72831707]])

In [5]:
arr_2 = np.where(arr_1<0,0,arr_1)
arr_2

array([[0.        , 0.38268722],
       [0.        , 2.40503128],
       [3.57102452, 4.72831707]])

In [6]:
arr_2 = np.where(arr_2>0, True, arr_2)
arr_2

array([[0., 1.],
       [0., 1.],
       [1., 1.]])

In [7]:
arr_bool = np.array([True,True,True,False])
arr_bool.all()

False

In [8]:
arr_bool = np.array([True,True,True,False])
arr_bool.any()

True

In [9]:
arr_bool = np.array([[True,True],[False,True],[True,True]])
arr_bool

array([[ True,  True],
       [False,  True],
       [ True,  True]])

In [10]:
arr_bool.all(0)

array([False,  True])

In [11]:
arr_bool.all(1)

array([ True, False,  True])