In [1]:
import numpy as np

In [2]:
arr_2d = np.array([
    [0,5,10],
    [15,20,25],
    [30,35,40]
])
arr_2d

array([[ 0,  5, 10],
       [15, 20, 25],
       [30, 35, 40]])

In [3]:
arr_2d[0]

array([ 0,  5, 10])

In [4]:
arr_2d[0][0]

0

In [5]:
arr_2d[-1][-1]

40

In [6]:
arr_2d[-1][0]=99
arr_2d

array([[ 0,  5, 10],
       [15, 20, 25],
       [99, 35, 40]])

In [7]:
arr_2d[:,:]

array([[ 0,  5, 10],
       [15, 20, 25],
       [99, 35, 40]])

In [8]:
arr_2d[:2,:]

array([[ 0,  5, 10],
       [15, 20, 25]])

In [9]:
arr_2d[:,:1]

array([[ 0],
       [15],
       [99]])

In [10]:
arr_2d[:,1:2]=0
arr_2d

array([[ 0,  0, 10],
       [15,  0, 25],
       [99,  0, 40]])

In [11]:
arr_2d = np.zeros((5,10))
arr_2d

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [12]:
arr_2d[2]=10
arr_2d

array([[ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [10., 10., 10., 10., 10., 10., 10., 10., 10., 10.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.]])

In [13]:
arr_2d[[0,2,-1]]=99
arr_2d

array([[99., 99., 99., 99., 99., 99., 99., 99., 99., 99.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [99., 99., 99., 99., 99., 99., 99., 99., 99., 99.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [99., 99., 99., 99., 99., 99., 99., 99., 99., 99.]])

In [14]:
arr_2d[[0,0,1,1,-1,-1]]

array([[99., 99., 99., 99., 99., 99., 99., 99., 99., 99.],
       [99., 99., 99., 99., 99., 99., 99., 99., 99., 99.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [99., 99., 99., 99., 99., 99., 99., 99., 99., 99.],
       [99., 99., 99., 99., 99., 99., 99., 99., 99., 99.]])

In [15]:
for row in arr_2d:
    print(row)

[99. 99. 99. 99. 99. 99. 99. 99. 99. 99.]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[99. 99. 99. 99. 99. 99. 99. 99. 99. 99.]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[99. 99. 99. 99. 99. 99. 99. 99. 99. 99.]


In [17]:
for i, row in enumerate(arr_2d):
    arr_2d[i]=i
arr_2d

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [3., 3., 3., 3., 3., 3., 3., 3., 3., 3.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.]])