In [1]:
import numpy as np

In [3]:
arr_1 = np.arange(1,6)
arr_2 = np.array([-3,7,3,13,0])
arr_1,arr_2

(array([1, 2, 3, 4, 5]), array([-3,  7,  3, 13,  0]))

In [4]:
np.add(arr_1,arr_2)

array([-2,  9,  6, 17,  5])

In [5]:
np.subtract(arr_1,arr_2)

array([ 4, -5,  0, -9,  5])

In [6]:
np.sqrt(arr_1)

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798])

In [7]:
np.power(arr_1,2)

array([ 1,  4,  9, 16, 25], dtype=int32)

In [8]:
np.sign(arr_1)

array([1, 1, 1, 1, 1])

In [9]:
np.sin(arr_1)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 , -0.95892427])

In [10]:
np.cos(arr_1)

array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362,  0.28366219])

In [11]:
np.tan(arr_1)

array([ 1.55740772, -2.18503986, -0.14254654,  1.15782128, -3.38051501])

In [12]:
np.deg2rad(arr_1)

array([0.01745329, 0.03490659, 0.05235988, 0.06981317, 0.08726646])

In [15]:
np.maximum(arr_1,arr_2)

array([ 1,  7,  3, 13,  5])

In [17]:
np.equal(arr_1,arr_2)

array([False, False,  True, False, False])

In [18]:
np.greater(arr_1,arr_2)

array([ True, False, False, False,  True])

In [19]:
arr_3 = np.array([3.14,2.57,-6.4,0.47,5.5])
arr_3

array([ 3.14,  2.57, -6.4 ,  0.47,  5.5 ])

In [20]:
np.fabs(arr_3)

array([3.14, 2.57, 6.4 , 0.47, 5.5 ])

In [21]:
np.ceil(arr_3)

array([ 4.,  3., -6.,  1.,  6.])

In [22]:
np.floor(arr_3)

array([ 3.,  2., -7.,  0.,  5.])

In [23]:
np.round(arr_3)

array([ 3.,  3., -6.,  0.,  6.])