In [1]:
import numpy as np

In [2]:
arr_1 = np.array([1,2,3,4])
arr_2 = np.array([5,6,7,8])

In [4]:
arr_1+arr_2

array([ 6,  8, 10, 12])

In [5]:
arr_3 = np.array([9,10])

In [6]:
arr_2 + arr_3

ValueError: operands could not be broadcast together with shapes (4,) (2,) 

In [7]:
arr_2-arr_1

array([4, 4, 4, 4])

In [8]:
arr_1-arr_1

array([0, 0, 0, 0])

In [9]:
arr_1*arr_2

array([ 5, 12, 21, 32])

In [10]:
arr_1*2

array([2, 4, 6, 8])

In [14]:
arr_4=np.array(2)
arr_4

array(2)

In [15]:
arr_1*arr_4

array([2, 4, 6, 8])

In [16]:
arr_1/arr_2

array([0.2       , 0.33333333, 0.42857143, 0.5       ])

In [17]:
arr_1/2

array([0.5, 1. , 1.5, 2. ])

In [18]:
1/arr_1

array([1.        , 0.5       , 0.33333333, 0.25      ])

In [20]:
arr_1**-1.

array([1.        , 0.5       , 0.33333333, 0.25      ])

In [21]:
arr_1**arr_2

array([    1,    64,  2187, 65536])

In [23]:
arr_5=np.array([[1,2],[3,4]])
arr_6=np.array([[5,6],[7,8]])
arr_5+arr_6

array([[ 6,  8],
       [10, 12]])

In [24]:
arr_5*3

array([[ 3,  6],
       [ 9, 12]])

In [25]:
arr_7 = np.array([5,10])
arr_5*arr_7

array([[ 5, 20],
       [15, 40]])