In [1]:
import numpy as np
arr = np.random.randint(10,size=[2,3])
arr

array([[8, 7, 6],
       [5, 6, 8]])

In [7]:
arr.sum() #sumatorio

40

In [6]:
arr.mean() #media

6.666666666666667

In [5]:
arr.std() #desviacion estandard

1.1055415967851332

In [8]:
arr.var() 

1.222222222222222

In [9]:
arr = np.random.randint(-10,10,size=[3,3])
arr

array([[ 9, -6,  0],
       [ 0, -4, -9],
       [ 5, -2,  6]])

In [10]:
arr.sort()
arr

array([[-6,  0,  9],
       [-9, -4,  0],
       [-2,  5,  6]])

In [11]:
arr.sort(0)
arr

array([[-9, -4,  0],
       [-6,  0,  6],
       [-2,  5,  9]])