In [9]:
import numpy as np

#array = np.array([1, 2, 3, 4, 5, 6.123])
array = np.array(["hola","que","tal", 12])

print(type(array))
print(array.dtype)
print(array.ndim)
print(array.shape)

<class 'numpy.ndarray'>
<U11
1
(4,)


In [4]:
array = np.array([
    [1, 2, 3, 4, 5],
    [6, 7, 8, 9, 10]
])

In [5]:
print(type(array))
print(array.ndim)
print(array.shape)

<class 'numpy.ndarray'>
2
(2, 5)


In [10]:
np.zeros(3)

array([0., 0., 0.])

In [11]:
# %% Definir una tipica celda VSC

In [12]:
np.zeros([3,3])

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [13]:
np.ones([3,3])

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [14]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [15]:
#Rango de 0 a 4
np.arange(4)

array([0, 1, 2, 3])

In [16]:
#Rango de 0 a 4 decimal
np.arange(4.)

array([0., 1., 2., 3.])

In [17]:
#Rango de -3 a 4
np.arange(-3,3)

array([-3, -2, -1,  0,  1,  2])

In [18]:
#Rango de 0 a 20 cada 5 numeros
np.arange(0,20,5)

array([ 0,  5, 10, 15])

In [19]:
# OPERACIONES