In [1]:
import numpy as np

In [2]:
arr_1d = np.array(
    [1,2]
)
arr_1d

array([1, 2])

In [3]:
arr_2d=np.array([
    [1,2],
    [3,4]
])
arr_2d

array([[1, 2],
       [3, 4]])

In [4]:
arr_3d = np.array([
    [
        [1,2],
        [3,4]
    ],
    [
        [5,6],
        [7,8]
    ]
])
arr_3d

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [5]:
arr_4d = np.array([
    [
        [
            [1,2],
            [3,4]
        ],
        [
            [5,6],
            [7,8]
        ]
    ],
    [
        [
            [9,10],
            [11,12]
        ],
        [
            [13,14],
            [15,16]
        ]
    ]
])
arr_4d

array([[[[ 1,  2],
         [ 3,  4]],

        [[ 5,  6],
         [ 7,  8]]],


       [[[ 9, 10],
         [11, 12]],

        [[13, 14],
         [15, 16]]]])

In [6]:
arr_3d = np.zeros([2,2,2])
arr_3d

array([[[0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.]]])

In [7]:
arr_4d = np.ones([2,2,2,2])
arr_4d

array([[[[1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.]]],


       [[[1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.]]]])

In [8]:
arr_2d = np.arange(9).reshape(3,3)
arr_2d

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [9]:
arr_3d = np.arange(9).reshape(3,3,3)
arr_3d

ValueError: cannot reshape array of size 9 into shape (3,3,3)

In [10]:
arr_3d = np.arange(27).reshape(3,3,3)
arr_3d

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])