In [1]:
import numpy as np

In [2]:
arr = np.array([[1,2,3],[4,5,6]])
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [3]:
arr.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [4]:
arr.T.T

array([[1, 2, 3],
       [4, 5, 6]])

In [5]:
arr.swapaxes(0,1)

array([[1, 4],
       [2, 5],
       [3, 6]])

In [6]:
arr.swapaxes(1,0)

array([[1, 4],
       [2, 5],
       [3, 6]])

In [7]:
arr_3d = np.arange(8).reshape(2,2,2)
arr_3d

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [8]:
arr_3d.T

array([[[0, 4],
        [2, 6]],

       [[1, 5],
        [3, 7]]])

In [9]:
arr_3d.swapaxes(0,2)

array([[[0, 4],
        [2, 6]],

       [[1, 5],
        [3, 7]]])

In [10]:
arr_3d.swapaxes(0,1)

array([[[0, 1],
        [4, 5]],

       [[2, 3],
        [6, 7]]])