In [1]:
import numpy as np
arr_1 = np.random.randint(0,4,[3,3])
arr_1

array([[0, 3, 1],
       [1, 3, 3],
       [2, 3, 3]])

In [2]:
np.save('arr_1.npy',arr_1)

In [3]:
del(arr_1)
arr_1

NameError: name 'arr_1' is not defined

In [4]:
arr_1=np.load('arr_1.npy')
arr_1

array([[0, 3, 1],
       [1, 3, 3],
       [2, 3, 3]])

In [5]:
arr_1=np.random.randint(0,4,[3,3])
arr_2=np.random.randint(-4,0,[3,3])
arr_1,arr_2

(array([[1, 3, 3],
        [0, 2, 1],
        [0, 0, 2]]),
 array([[-4, -2, -1],
        [-4, -3, -2],
        [-3, -4, -3]]))

In [6]:
np.savez('arrays.npz',arr_1=arr_1,arr_2=arr_2)#claves

In [7]:
del(arr_1)
del(arr_2)

In [8]:
arrays = np.load('arrays.npz')
arrays

In [9]:
arrays['arr_1'],arrays['arr_2']

(array([[1, 3, 3],
        [0, 2, 1],
        [0, 0, 2]]),
 array([[-4, -2, -1],
        [-4, -3, -2],
        [-3, -4, -3]]))

In [10]:
arr_3=np.random.randint(-10,10,[3,3])
arr_3

array([[ 7,  3,  4],
       [ 8,  7,  8],
       [-7, -8,  6]])

In [11]:
np.savetxt('arr_3.txt',arr_3)

In [12]:
np.savetxt('arr_3.txt',arr_3,delimiter=',')

In [13]:
del(arr_3)

In [14]:
arr_3=np.loadtxt('arr_3.txt',delimiter=',')
arr_3

array([[ 7.,  3.,  4.],
       [ 8.,  7.,  8.],
       [-7., -8.,  6.]])