In [2]:
import numpy as np
np.random.rand()

0.5235928169487288

In [3]:
np.random.rand(4)

array([0.94731507, 0.86493497, 0.50659341, 0.60474163])

In [4]:
np.random.rand(4,2)

array([[0.00784538, 0.59954566],
       [0.24371726, 0.58021113],
       [0.24304185, 0.93592866],
       [0.77932984, 0.26827794]])

In [5]:
np.random.uniform(10,size=[2,2,2])

array([[[4.46661881, 8.33380993],
        [6.52968457, 4.80059132]],

       [[1.14197732, 5.49517237],
        [8.75948254, 9.95233301]]])

In [6]:
np.random.uniform(-10,10,size=[2,2,2,2])

array([[[[ 9.82306952,  8.93679888],
         [ 9.29854749, -5.43368   ]],

        [[-7.53473339,  2.22345549],
         [ 2.55685703,  3.58153034]]],


       [[[-7.96557584,  7.77486943],
         [ 5.78426486, -4.45979754]],

        [[-9.21777369, -5.58541445],
         [ 6.72160356, -9.60923082]]]])

In [7]:
np.random.randint(10)

0

In [8]:
np.random.randint(10, size=[3,2])

array([[1, 1],
       [9, 4],
       [9, 5]])

In [9]:
np.random.randint(-10,10, size=[3,2])

array([[-4,  1],
       [ 4, -3],
       [-8, -6]])

In [10]:
np.random.normal(size=100)

array([-0.06942544,  0.75534751, -2.07206785, -1.55645159, -1.50893598,
        0.59716795,  1.03202522,  0.66114536, -1.34353491,  0.51607964,
        1.04656824,  0.09038977,  1.20450868,  0.61652034, -1.08588148,
        0.14787114, -0.11935097, -1.21749918,  0.89238787, -1.17743485,
       -1.29546853, -0.20716866,  1.74615439, -0.03169875, -1.63060059,
       -0.06917648, -1.21335542, -0.98901905, -2.04970008,  0.62923438,
       -0.52865476, -1.10816035,  0.91991241,  0.45051496,  1.03977068,
        1.01458912,  0.48730871,  0.6614799 ,  2.10725364,  0.17227765,
       -0.89681742, -0.7506613 , -0.81885081,  0.79428773, -1.91260229,
       -0.23970301, -0.14440014, -1.63485045, -2.24022143,  0.55452476,
        0.20398603,  0.76022245, -0.572983  , -0.92335308, -1.00436795,
       -1.51897685,  0.35482811,  0.10091894,  0.03970589, -1.78444208,
        0.65483197,  0.28270838,  0.28172517,  0.60179238,  1.56773822,
        2.18457431, -0.01277658,  0.42430795,  0.06008489, -0.56

In [11]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
np.random.shuffle(arr)
arr

array([9, 5, 0, 8, 4, 1, 2, 3, 7, 6])

In [13]:
arr = np.random.permutation(10)
arr

array([6, 0, 7, 1, 2, 9, 5, 3, 4, 8])